#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the
# string Ceci n'est pas une page.

apt-get update
apt-get -y install nginx
mkdir /etc/nginx/html
echo "Hello World!" > /etc/nginx/html/index.html
echo "Ceci n'est pas une page" > /etc/nginx/html/404.html
sed -i '/^\sserver_name.*/a \ rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default
sed -i '/^\slocation.*/i \  error page 404 /custom_404.html;' /etc/nginx/sites-available/default
service nginx start
