#!/usr/bin/env bash
# web-01 and web-02 should be redundant. ie similar

# nginx installation
sudo apt-get -y update
sudo apt-get -y install nginx

# Redirection
sudo sed -i '/^\server_name.*/a \  rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Not found page 404
sudo sed -i '/^\slocation.*/i \  error_page 404 /custom_404.html;' /etc/nginx/sites-available/default

# custom response header
sudo sed -i '/^\slocation.*/i \  add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# start server
sudo service nginx start
