#!/usr/bin/env bash
# Write a Bash script that configures a server to the above requirements
sudo service nginx stop
sudo kill nginx
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx stop
