#!/usr/bin/env bash
# Write a Bash script that configures a server to the above requirements
sed -i 's/[0-9]\+ default_server/80 default_server/' /etc/nginx/sites-enabled/default
sudo service nginx restart
