#!/usr/bin/env bash
# Write a Bash script that configures a server to the above requirements
sudo kill nginx
sudo sed -i '21s|listen 8080 default_server;|listen 80 default_server;|'\
     /etc/nginx/sites-enabled/defaults
sudo service nginx start
