#!/usr/bin/env bash
# Write a Bash script that configures a server to the above requirements
sed -i "s/8080/80/g" /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo rm /var/run/nginx.pid
