#!/usr/bin/env bash
#print To infinity and beyond infinetly

trap 'echo "I hate the kill command"' 15
trap 'echo "Y U no love me?!"' 2

echo $$ >> /var/run/myscript.pid
while true
do
        echo "To infinity and beyond"
done
rm /var/run/myscript.pid