#!/usr/bin/env bash
#lets print "Best School" x10 using a while loop
#at 9 print Hi

n=1
while((n <= 20))
do
	case $n in
	     	4)
			echo "$n"
			echo $"bad luck from China"
			;;
		9)
			echo "$n"
			echo $"bad luck from Japan"
			;;
		17)
			echo "$n"
			echo $"bad luck from Italy"
			;;
		*)
			echo "$n"
			;;
	esac
	((n++))
done